name: dbt prod

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install requirements
        run: pip install -q dbt-postgres datafold-sdk

      - name: dbt deps
        run: dbt deps

      - name: dbt seed
        run: "dbt seed --full-refresh --vars '{load_source_data: true}' --profiles-dir ./"
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_SCHEMA: public

      - name: dbt build
        run: dbt build --profiles-dir ./
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_SCHEMA: public

      - name: submit artifacts to datafold
        run: |
          set -ex
          datafold dbt upload --ci-config-id ${DATAFOLD_CI_CONFIG_ID} --run-type ${DATAFOLD_RUN_TYPE} --commit-sha ${GIT_SHA}
        env:
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_APIKEY }}
          DATAFOLD_CI_CONFIG_ID: ${{ secrets.DATAFOLD_CI_CONFIG_ID }}
          DATAFOLD_RUN_TYPE: production
          GIT_SHA: ${{ github.sha }}
